/// Returns the UPnP device description XML for a MediaRenderer.
String deviceDescriptionXml({
  required String uuid,
  required String friendlyName,
  required String baseUrl,
}) {
  return '<?xml version="1.0" encoding="utf-8"?>'
      '<root xmlns="urn:schemas-upnp-org:device-1-0">'
      '<specVersion><major>1</major><minor>0</minor></specVersion>'
      '<device>'
      '<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>'
      '<friendlyName>$friendlyName</friendlyName>'
      '<manufacturer>Hearth</manufacturer>'
      '<manufacturerURL>https://github.com/hearth-home</manufacturerURL>'
      '<modelDescription>Hearth Smart Home Kiosk</modelDescription>'
      '<modelName>Hearth</modelName>'
      '<modelNumber>1</modelNumber>'
      '<UDN>uuid:$uuid</UDN>'
      '<serviceList>'
      '<service>'
      '<serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>'
      '<serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>'
      '<SCPDURL>/dlna/AVTransport.xml</SCPDURL>'
      '<controlURL>/dlna/AVTransport/control</controlURL>'
      '<eventSubURL>/dlna/AVTransport/event</eventSubURL>'
      '</service>'
      '<service>'
      '<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>'
      '<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>'
      '<SCPDURL>/dlna/RenderingControl.xml</SCPDURL>'
      '<controlURL>/dlna/RenderingControl/control</controlURL>'
      '<eventSubURL>/dlna/RenderingControl/event</eventSubURL>'
      '</service>'
      '<service>'
      '<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>'
      '<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>'
      '<SCPDURL>/dlna/ConnectionManager.xml</SCPDURL>'
      '<controlURL>/dlna/ConnectionManager/control</controlURL>'
      '<eventSubURL>/dlna/ConnectionManager/event</eventSubURL>'
      '</service>'
      '</serviceList>'
      '</device>'
      '</root>';
}

/// Returns the AVTransport service description (SCPD) XML.
String avTransportScpd() {
  return '<?xml version="1.0" encoding="utf-8"?>'
      '<scpd xmlns="urn:schemas-upnp-org:service-1-0">'
      '<specVersion><major>1</major><minor>0</minor></specVersion>'
      '<actionList>'
      // SetAVTransportURI
      '<action>'
      '<name>SetAVTransportURI</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '<argument><name>CurrentURI</name><direction>in</direction><relatedStateVariable>AVTransportURI</relatedStateVariable></argument>'
      '<argument><name>CurrentURIMetaData</name><direction>in</direction><relatedStateVariable>AVTransportURIMetaData</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // Play
      '<action>'
      '<name>Play</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '<argument><name>Speed</name><direction>in</direction><relatedStateVariable>TransportPlaySpeed</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // Pause
      '<action>'
      '<name>Pause</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // Stop
      '<action>'
      '<name>Stop</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // Seek
      '<action>'
      '<name>Seek</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '<argument><name>Unit</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_SeekMode</relatedStateVariable></argument>'
      '<argument><name>Target</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_SeekTarget</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // GetPositionInfo
      '<action>'
      '<name>GetPositionInfo</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '<argument><name>Track</name><direction>out</direction><relatedStateVariable>CurrentTrack</relatedStateVariable></argument>'
      '<argument><name>TrackDuration</name><direction>out</direction><relatedStateVariable>CurrentTrackDuration</relatedStateVariable></argument>'
      '<argument><name>TrackMetaData</name><direction>out</direction><relatedStateVariable>CurrentTrackMetaData</relatedStateVariable></argument>'
      '<argument><name>TrackURI</name><direction>out</direction><relatedStateVariable>CurrentTrackURI</relatedStateVariable></argument>'
      '<argument><name>RelTime</name><direction>out</direction><relatedStateVariable>RelativeTimePosition</relatedStateVariable></argument>'
      '<argument><name>AbsTime</name><direction>out</direction><relatedStateVariable>AbsoluteTimePosition</relatedStateVariable></argument>'
      '<argument><name>RelCount</name><direction>out</direction><relatedStateVariable>RelativeCounterPosition</relatedStateVariable></argument>'
      '<argument><name>AbsCount</name><direction>out</direction><relatedStateVariable>AbsoluteCounterPosition</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // GetTransportInfo
      '<action>'
      '<name>GetTransportInfo</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '<argument><name>CurrentTransportState</name><direction>out</direction><relatedStateVariable>TransportState</relatedStateVariable></argument>'
      '<argument><name>CurrentTransportStatus</name><direction>out</direction><relatedStateVariable>TransportStatus</relatedStateVariable></argument>'
      '<argument><name>CurrentSpeed</name><direction>out</direction><relatedStateVariable>TransportPlaySpeed</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // GetMediaInfo
      '<action>'
      '<name>GetMediaInfo</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '<argument><name>NrTracks</name><direction>out</direction><relatedStateVariable>NumberOfTracks</relatedStateVariable></argument>'
      '<argument><name>MediaDuration</name><direction>out</direction><relatedStateVariable>CurrentMediaDuration</relatedStateVariable></argument>'
      '<argument><name>CurrentURI</name><direction>out</direction><relatedStateVariable>AVTransportURI</relatedStateVariable></argument>'
      '<argument><name>CurrentURIMetaData</name><direction>out</direction><relatedStateVariable>AVTransportURIMetaData</relatedStateVariable></argument>'
      '<argument><name>NextURI</name><direction>out</direction><relatedStateVariable>NextAVTransportURI</relatedStateVariable></argument>'
      '<argument><name>NextURIMetaData</name><direction>out</direction><relatedStateVariable>NextAVTransportURIMetaData</relatedStateVariable></argument>'
      '<argument><name>PlayMedium</name><direction>out</direction><relatedStateVariable>PlaybackStorageMedium</relatedStateVariable></argument>'
      '<argument><name>RecordMedium</name><direction>out</direction><relatedStateVariable>RecordStorageMedium</relatedStateVariable></argument>'
      '<argument><name>WriteStatus</name><direction>out</direction><relatedStateVariable>RecordMediumWriteStatus</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      '</actionList>'
      '<serviceStateTable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_InstanceID</name><dataType>ui4</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_SeekMode</name><dataType>string</dataType>'
      '<allowedValueList><allowedValue>REL_TIME</allowedValue><allowedValue>TRACK_NR</allowedValue></allowedValueList>'
      '</stateVariable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_SeekTarget</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>TransportState</name><dataType>string</dataType>'
      '<allowedValueList><allowedValue>STOPPED</allowedValue><allowedValue>PLAYING</allowedValue><allowedValue>PAUSED_PLAYBACK</allowedValue><allowedValue>TRANSITIONING</allowedValue><allowedValue>NO_MEDIA_PRESENT</allowedValue></allowedValueList>'
      '</stateVariable>'
      '<stateVariable sendEvents="no"><name>TransportStatus</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>TransportPlaySpeed</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="yes"><name>AVTransportURI</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>AVTransportURIMetaData</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>CurrentTrack</name><dataType>ui4</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>CurrentTrackDuration</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>CurrentTrackMetaData</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>CurrentTrackURI</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>RelativeTimePosition</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>AbsoluteTimePosition</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>RelativeCounterPosition</name><dataType>i4</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>AbsoluteCounterPosition</name><dataType>i4</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>NumberOfTracks</name><dataType>ui4</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>CurrentMediaDuration</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>NextAVTransportURI</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>NextAVTransportURIMetaData</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>PlaybackStorageMedium</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>RecordStorageMedium</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>RecordMediumWriteStatus</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="yes"><name>LastChange</name><dataType>string</dataType></stateVariable>'
      '</serviceStateTable>'
      '</scpd>';
}

/// Returns the RenderingControl service description (SCPD) XML.
String renderingControlScpd() {
  return '<?xml version="1.0" encoding="utf-8"?>'
      '<scpd xmlns="urn:schemas-upnp-org:service-1-0">'
      '<specVersion><major>1</major><minor>0</minor></specVersion>'
      '<actionList>'
      // GetVolume
      '<action>'
      '<name>GetVolume</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '<argument><name>Channel</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable></argument>'
      '<argument><name>CurrentVolume</name><direction>out</direction><relatedStateVariable>Volume</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // SetVolume
      '<action>'
      '<name>SetVolume</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '<argument><name>Channel</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable></argument>'
      '<argument><name>DesiredVolume</name><direction>in</direction><relatedStateVariable>Volume</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // GetMute
      '<action>'
      '<name>GetMute</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '<argument><name>Channel</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable></argument>'
      '<argument><name>CurrentMute</name><direction>out</direction><relatedStateVariable>Mute</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // SetMute
      '<action>'
      '<name>SetMute</name>'
      '<argumentList>'
      '<argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>'
      '<argument><name>Channel</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable></argument>'
      '<argument><name>DesiredMute</name><direction>in</direction><relatedStateVariable>Mute</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      '</actionList>'
      '<serviceStateTable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_InstanceID</name><dataType>ui4</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_Channel</name><dataType>string</dataType>'
      '<allowedValueList><allowedValue>Master</allowedValue></allowedValueList>'
      '</stateVariable>'
      '<stateVariable sendEvents="no"><name>Volume</name><dataType>ui2</dataType>'
      '<allowedValueRange><minimum>0</minimum><maximum>100</maximum><step>1</step></allowedValueRange>'
      '</stateVariable>'
      '<stateVariable sendEvents="no"><name>Mute</name><dataType>boolean</dataType></stateVariable>'
      '<stateVariable sendEvents="yes"><name>LastChange</name><dataType>string</dataType></stateVariable>'
      '</serviceStateTable>'
      '</scpd>';
}

/// Returns the ConnectionManager service description (SCPD) XML.
String connectionManagerScpd() {
  return '<?xml version="1.0" encoding="utf-8"?>'
      '<scpd xmlns="urn:schemas-upnp-org:service-1-0">'
      '<specVersion><major>1</major><minor>0</minor></specVersion>'
      '<actionList>'
      // GetProtocolInfo
      '<action>'
      '<name>GetProtocolInfo</name>'
      '<argumentList>'
      '<argument><name>Source</name><direction>out</direction><relatedStateVariable>SourceProtocolInfo</relatedStateVariable></argument>'
      '<argument><name>Sink</name><direction>out</direction><relatedStateVariable>SinkProtocolInfo</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // GetCurrentConnectionIDs
      '<action>'
      '<name>GetCurrentConnectionIDs</name>'
      '<argumentList>'
      '<argument><name>ConnectionIDs</name><direction>out</direction><relatedStateVariable>CurrentConnectionIDs</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      // GetCurrentConnectionInfo
      '<action>'
      '<name>GetCurrentConnectionInfo</name>'
      '<argumentList>'
      '<argument><name>ConnectionID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_ConnectionID</relatedStateVariable></argument>'
      '<argument><name>RcsID</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_RcsID</relatedStateVariable></argument>'
      '<argument><name>AVTransportID</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_AVTransportID</relatedStateVariable></argument>'
      '<argument><name>ProtocolInfo</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_ProtocolInfo</relatedStateVariable></argument>'
      '<argument><name>PeerConnectionManager</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_ConnectionManager</relatedStateVariable></argument>'
      '<argument><name>PeerConnectionID</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_ConnectionID</relatedStateVariable></argument>'
      '<argument><name>Direction</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_Direction</relatedStateVariable></argument>'
      '<argument><name>Status</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_ConnectionStatus</relatedStateVariable></argument>'
      '</argumentList>'
      '</action>'
      '</actionList>'
      '<serviceStateTable>'
      '<stateVariable sendEvents="yes"><name>SourceProtocolInfo</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="yes"><name>SinkProtocolInfo</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="yes"><name>CurrentConnectionIDs</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_ConnectionID</name><dataType>i4</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_RcsID</name><dataType>i4</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_AVTransportID</name><dataType>i4</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_ProtocolInfo</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_ConnectionManager</name><dataType>string</dataType></stateVariable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_Direction</name><dataType>string</dataType>'
      '<allowedValueList><allowedValue>Input</allowedValue><allowedValue>Output</allowedValue></allowedValueList>'
      '</stateVariable>'
      '<stateVariable sendEvents="no"><name>A_ARG_TYPE_ConnectionStatus</name><dataType>string</dataType>'
      '<allowedValueList><allowedValue>OK</allowedValue><allowedValue>Unknown</allowedValue></allowedValueList>'
      '</stateVariable>'
      '</serviceStateTable>'
      '</scpd>';
}
